### ISSUE TITLE
Show last build timestamp

### ISSUE THREAD

**Issue by mfriedenhagen** [jan-molak/jenkins-build-monitor-plugin#120]
We use the plugin for monitoring cron jobs run regularly. It would be great if it could show a timestamp for the last build.

**Comment by mfriedenhagen** [comment]
Duplicates #63

**Comment by mfriedenhagen** [comment]
This issue somehow is related to #63, however the patch provided in #63 does update the period since the last build every five seconds, which makes the screen look quite busy when you have more than a couple of jobs. IMO it would be sufficient to have a timestamp of the form `YY-MM-DD hh:mm` which should be enough to see when a job has not run for a long while.

**Comment by bernardomaciel** [comment]
+1

**Comment by jan-molak** [comment]
Hey @mfriedenhagen , I'm working on a patch based on #63. I agree with your view that even though the overall implementation proposed in the pull request looks good, it could result in the display looking a bit busy.

What I'm thinking of doing is decreasing the precision over time so that the display doesn't "seem" to be updated more often than it needs to. This would result in something along the lines of the following:
- for builds that run between 0 and 1h ago display the time elapsed with a minute precision, ie. "17 minutes ago"
- for builds that run over an hour ago display the time elapsed with an hourly precision ie. "2 hours ago" rather than "1 hour 45 minutes ago"
- for even older builds the precision would further decrease, ie. "2 days ago", etc.

Would this approach work with your use case?

**Comment by mfriedenhagen** [comment]
@jan-molak, sound like a good direction. My only concern are updates of the UI every 5 seconds, once a minute for the first hour after a run is OK for me :+1: What about rounding? 1:30h would already be 2h then?

**Comment by jan-molak** [comment]
@mfriedenhagen - I'd love to hear your feedback on the [latest build](https://smartcode-opensource.ci.cloudbees.com/job/jenkins-build-monitor-plugin/140/artifact/target/build-monitor-plugin.hpi)

**Comment by mfriedenhagen** [comment]
@jan-molak , great visualization :+1:
