### ISSUE TITLE
Last build duration is not correct

### ISSUE THREAD

**Issue by bernardomaciel** [jan-molak/jenkins-build-monitor-plugin#131]
Hi,

Thanks for this great plugin.
I have noticed that last build duration is not being displayed correctly.
Using Jenkins ver. 1.598 (on Win 7 64-bit) with Build Monitor plugin v1.6+build.138 and Chromium Portable Version 39.0.2150.5 (7d466dc36d619ad23f32fabff9fc9bab25fbab58) (64-bit) (on Win 7 64-bit).

Check the screenshots below:

![Jenkins Dashboard](http://s27.postimg.org/i58496rk3/screencapture_jenkins_dashboard.jpg)

![Status Monitor](http://s27.postimg.org/402b7diir/screencapture_view_Status_Monitor.jpg)

Regards,

Bernardo Maciel

**Comment by jan-molak** [comment]
Hi @bernardomaciel and thanks for your feedback. I'm happy to hear that you find the Build Monitor useful :-)

The time in the bottom right corner is not the time Jenkins took to complete the last build, but the time it _usually takes_ to complete a build of this particular build job. Please have a look at #76 for further explanation.
Having said that, since you're the second person who found this confusing, I'll think of a way to make this more obvious :-)

Best,
Jan

**Comment by bernardomaciel** [comment]
OK @jan-molak .
Thanks for clarifying.
Perhaps you could add a tooltip with more info (e.g., with the last release, "Last build time")..
