### ISSUE TITLE
Job name not visible when there are a lot of "culprits"

### ISSUE THREAD

**Issue by antonyj75** [jan-molak/jenkins-build-monitor-plugin#138]
It is no longer possible to see the job name when there are lot of culprits. As a result, it is not clear which job is broken. You will have to click on it and go to the job to see which job it is. This is not a good situation for a big monitor view.
![buildmonitorview](https://cloud.githubusercontent.com/assets/4309910/6851453/746014a0-d3df-11e4-93f4-cbddf92ed2c5.png)

**Comment by jan-molak** [comment]
Hey @antonyj75 and thanks for your feedback. This request seems similar to what @patrickdepinguin asked for in #70. I'll be looking into addressing the way this information is displayed soon.

In the meantime though, I see that the top four builds from your screenshot haven't run in 10 days. Would it possible for them to be executed more often, therefore limiting the amount of change per build?

Best,
Jan

**Comment by patrickdepinguin** [comment]
@jan-molak have you noticed that there is a pull request #116 pending that implements this feature?

**Comment by jan-molak** [comment]
Yes, I have, thanks for that PR, Patrick! I'm not yet sure though if hiding the culprits alltogether is the best solution to this problem... Let me elaborate a bit more.

It seems to me that the underlying problem here is that the builds are not executed often enough; too many changes git picked up by Jenkins and the list of possible culprits gets long.

From what I have observed this is a common scenario if the team runs nightly (or weekly) builds rather than executing a build per commit (or polling the VCS for changes every couple of minutes).
This practice usually results in a difficult troubleshooting process, as it's hard to tell what broke the build if you have to review (and potentially fix) code changes that came in from 30 people in order to make the build pass again...

Having said that, I agree that the visualisation should be improved and loosing the name of the build job from the view is definitely not good enough :-)

Instead of hiding the list of culprits though I'm thinking of displaying this information in a "facebook like button" style, so maybe:
```
Possible culprits: Adam Ipsum and 27 others
```

What do you think?

**Comment by patrickdepinguin** [comment]
@jan-molak I don't think that the build-monitor plugin should try and dictate such policies onto its users. There may be very good reasons why a team can only run their tests once a day and thus have a long culprit lists. One such reason could be the limited availability of resources, or the long duration of an individual test run in very complex systems.
For this reason, I believe the plugin should be flexible and allow for some configuration.

Besides this, you should be aware of cultural issues. In some cultures (ethnical cultures or company cultures) it is considered inappropriate to blame people publicly on a wall display. Hiding the culprit list would work perfectly in such cases. 
Having a 'Adam Ipsum and 27 others' text could even be worse, as now Adam seems to be blamed prominently while he could be totally innocent.

**Comment by PezHead** [comment]
@jan-molak Our team runs builds with every code push. This includes jobs for both building our projects as well as running automated functional testing. Even though we run the jobs multiple times per day, we have so much activity in our mercurial repo for automated tests that we still have the problem that the screen is just filled up with the blame list when a job fails.

Having a condensed culprit would be helpful in allowing us to still see the job name, though being able to hide it all together would be preferable.

**Comment by antonyj75** [comment]
@jan-molak <https://github.com/jan-molak>  and others:

Thank you for your email.

 

Is it possible to provide an option to enable/disable the display of culprits?

 

We have several jobs that run at code commit.

There are also some performance jobs that we run daily, weekly, and monthly.

We do not want to see the culprit list in these jobs, because as you can see, the list could be large.

 

Therefore, it would be great if we are able to enable/disable the display of culprits.

For example:

    Show culprits

When checked, the culprit list is shown.

 

Thank you. Have a nice day!

 

With kind regards,

Antony

 

Mass production of food is evil.

Foodstuff is best when produced by local farmers.

Want to know why? Watch  <http://documentarylovers.com/film/food-inc/> Food Inc.

**Comment by jan-molak** [comment]
Good points, guys. I really appreciate your comments.

While I completely agree that the issue with job names getting out of view needs to be fixed, I'm wondering if the [Claim plugin](https://github.com/jan-molak/jenkins-build-monitor-plugin#how-do-i-let-my-teammates-know-that-im-fixing-a-broken-build) could help in scenarios you've described above?

Let me think out loud for a moment.

Claiming a broken build does several things:
- hides the list of culprits
- clearly indicates who's working on fixing the build so others can help him
- helps to prioritise work

It seems that we talked about four scenarios so far:

#### 1. Long-running builds

Builds can take a long time time to run because of bad reasons, i.e. using web browser-based tests to exercise the whole application stack where unit tests would suffice, or because of perfectly good reasons, like running system soak tests or performance tests for example.

In either case, I'd prefer to see at a glance how badly a build is broken, if it's broken. 
* If it contains 120 changes from 27 authors and nobody is working on it yet (it's not been claimed) it's probably not going to be trivial to fix. You might need the entire team to drop the tools and fix the problem.
* If it contains a couple of changes from one to maybe a handful of authors someone can easily pick this up. The situation is not good, but we're not doomed yet :-)
* If it's already been claimed I can easily tell who's on the case and offer them help if they need it.

#### 2. Limited resources

Limited resources might lead to running builds less often. I'd argue that the situation here is same as above. If it's broken - you can claim it.

#### 3. Higly active projects with a lot of change

It doesn't seem like the volume of change should justify leaving the build red?
I usually work on projects with hundreds of developers and a lot of change, but even on those project if the build is broken you shouldn't be pushing new changes unless they're to fix the failure. Should you?

And if you're the one fixing the build - again, you can claim it.

#### 4. Lack of transparency

Now, here's a tricky one... The main purpose of Build Monitor is to help enable transparency. How to deal with a situation where transparency is not desired?

Even in such a situation I'd still like to know how badly a build is broken, and if someone is on it.

Claiming should again do the trick, but what if the build has not been claimed (yet)?

Maybe displaying something along the lines of the following could help to determine the scale of the damage?

```
           < job name >
Contains 120 changes by 27 authors
```

Actually, this information could also be displayed if a build is claimed...

Looking forward to hearing your thoughts!

**Comment by antonyj75** [comment]
Hi Jan,
Good morning.Thank you for your quick response.
Beyond the four scenarios, the source control and claim plugins have their limitations as well.
Some examples are:
- I've seen that the list of culprits is not always correct. This is because, the list of contributors keep changing with multiple runs of the failed job. If you want to see the actual potential culprits, then you need to see the first time failure of the job. Subsequent failed builds of the job only show the contributors to those respective builds.
- We have a gerrit automatic review system that also does commits to git. In this case, the possible culprit is shown as "gerrit". This gives no idea who the real culprit is.
- You could only claim a failed build. We have several jobs that could be "unstable" when the coverage or coverity or test failures are within a threshold. The claim plugin does not provide a way to claim unstable builds. Therefore we are in the same situation where the job name is not visible. This does not provide a good experience when we have the monitor on the wall.

Your idea of displaying something like

           < job name >
Contains 120 changes by 27 authors

sounds good to me.

So I request to either provide this functionality or give an option to hide/display the list of culprits in the configure screen.
In view of your desire to keep the plugin as simple as possible, I believe doing this will help keeping the display of data simple. :-) 
Thank you!
With kind regards,Antony



     On Monday, March 30, 2015 6:35 PM, Jan Molak <notifications@github.com> wrote:
   

 Good points, guys. I really appreciate your comments.While I completely agree that the issue with job names getting out of view needs to be fixed, I'm wondering if the Claim plugin could help in scenarios you've described above?Let me think out loud for a moment.Claiming a broken build does several things:   
   - hides the list of culprits
   - clearly indicates who's working on fixing the build so others can help him
   - helps to prioritise work
It seems that we talked about four scenarios so far:
1. Long-running builds
Builds can take a long time time to run because of bad reasons, i.e. using web browser-based tests to exercise the whole application stack where unit tests would suffice, or because of perfectly good reasons, like running system soak tests or performance tests for example.In either case, I'd prefer to see at a glance how badly a build is broken, if it's broken.    
   - If it contains 120 changes from 27 authors and nobody is working on it yet (it's not been claimed) it's probably not going to be trivial to fix. You might need the entire team to drop the tools and fix the problem.
   - If it contains a couple of changes from one to maybe a handful of authors someone can easily pick this up. The situation is not good, but we're not doomed yet :-)
   - If it's already been claimed I can easily tell who's on the case and offer them help if they need it.

2. Limited resources
Limited resources might lead to running builds less often. I'd argue that the situation here is same as above. If it's broken - you can claim it.
3. Higly active projects with a lot of change
It doesn't seem like the volume of change should justify leaving the build red?
I usually work on projects with hundreds of developers and a lot of change, but even on those project if the build is broken you shouldn't be pushing new changes unless they're to fix the failure. Should you?And if you're the one fixing the build - again, you can claim it.
4. Lack of transparency
Now, here's a tricky one... The main purpose of Build Monitor is to help enable transparency. How to deal with a situation where transparency is not desired?Even in such a situation I'd still like to know how badly a build is broken, and if someone is on it.Claiming should again do the trick, but what if the build has not been claimed (yet)?Maybe displaying something along the lines of the following could help to determine the scale of the damage?           < job name >
Contains 120 changes by 27 authors
Actually, this information could also be displayed if a build is claimed...Looking forward to hearing your thoughts!—

**Comment by jan-molak** [comment]
Hi Antony and thanks for pointing those out.

> I've seen that the list of culprits is not always correct. This is because, the list of contributors keep changing with multiple runs of the failed job. If you want to see the actual potential culprits, then you need to see the first time failure of the job. Subsequent failed builds of the job only show the contributors to those respective builds.

That's an intentional behaviour; The idea here is to avoid people committing code on a broken build. 

> We have a gerrit automatic review system that also does commits to git. In this case, the possible culprit is shown as "gerrit". This gives no idea who the real culprit is.

I see, I thought that this [could be configured](http://wiki.qt.io/Setting-up-Gerrit)?

> You could only claim a failed build. We have several jobs that could be "unstable" when the coverage or coverity or test failures are within a threshold. The claim plugin does not provide a way to claim unstable builds. Therefore we are in the same situation where the job name is not visible. This does not provide a good experience when we have the monitor on the wall.

I usually avoid using the concept of *unstable builds* because of the reasons I talk more about in my article ["The bad case of rotting builds"](http://smartcodeltd.co.uk/blog/2014/10/16/communicating-build-status-better-with-jenkins-and-the-build-monitor-plugin/). 
Nevertheless, I believe that the issue you've observed with the Claim plugin has been fixed in 2.5 ([JENKINS-23513](https://issues.jenkins-ci.org/browse/JENKINS-23513)) so you might want to give that version a try?


Having said all the above, I really appreciate your feedback guys and agree that it should be up to the team to decide whether showing the list of possible culprits helps them or not.
I'll get get #116 merged soon, so stay tuned! :-)

Thanks for sharing your thoughts!

Best,
Jan

**Comment by antonyj75** [comment]
Thank you Jan for your detailed response, and sharing insights about gerrit configuration and claim plugin.

I will talk to the responsibles in our team to see if this could be done better.

 

A big thanks for merging #116 as well. J

 

Have a nice day!

 

With kind regards,

Antony

 

Mass production of food is evil.

Foodstuff is best when produced by local farmers.

Want to know why? Watch  <http://documentarylovers.com/film/food-inc/> Food Inc.

**Comment by antonyj75** [comment]
Hi Jan,
We updated the plugin and used the "Show possible culprits?" option.Simply put: works like a charm.
Thanks a lot for getting this done so quickly.
With kind regards,Antony 


     On Thursday, April 2, 2015 12:41 PM, Jan Molak <notifications@github.com> wrote:
   

 Hi Antony and thanks for pointing those out.
I've seen that the list of culprits is not always correct. This is because, the list of contributors keep changing with multiple runs of the failed job. If you want to see the actual potential culprits, then you need to see the first time failure of the job. Subsequent failed builds of the job only show the contributors to those respective builds.
That's an intentional behaviour; The idea here is to avoid people committing code on a broken build. 
We have a gerrit automatic review system that also does commits to git. In this case, the possible culprit is shown as "gerrit". This gives no idea who the real culprit is.
I see, I thought that this could be configured?
You could only claim a failed build. We have several jobs that could be "unstable" when the coverage or coverity or test failures are within a threshold. The claim plugin does not provide a way to claim unstable builds. Therefore we are in the same situation where the job name is not visible. This does not provide a good experience when we have the monitor on the wall.
I usually avoid using the concept of unstable builds because of the reasons I talk more about in my article "The bad case of rotting builds". 
Nevertheless, I believe that the issue you've observed with the Claim plugin has been fixed in 2.5 (JENKINS-23513) so you might want to give that version a try?Having said all the above, I really appreciate your feedback guys and agree that it should be up to the team to decide whether showing the list of possible culprits helps them or not.
I'll get get #116 merged soon, so stay tuned! :-)Thanks for sharing your thoughts!Best,
Jan—

**Comment by antonyj75** [comment]
Thank you, it is working fine! J

 

With kind regards,

Antony

 

Mass production of food is evil.

Foodstuff is best when produced by local farmers.

Want to know why? Watch  <http://documentarylovers.com/film/food-inc/> Food Inc.

**Comment by jan-molak** [comment]
Great, I'm glad to hear that you like this solution :smile: 

I'll release the latest version of Build Monitor to Jenkins Update Centre next week, but if you'd like to take it for a spin before that you can always [download it here](https://smartcode-opensource.ci.cloudbees.com/job/jenkins-build-monitor-plugin/171/artifact/target/build-monitor-plugin.hpi).
