### ISSUE TITLE
connection error message popup is modal, and stops automatic refresh

### ISSUE THREAD

**Issue by marc-guenther** [jan-molak/jenkins-build-monitor-plugin#150]
We are using this for one day now, and every couple of hours, it pops up this error message:
## Sorry to bother you, but there is a slight issue ...
    Jenkins returned a "502" response causing the last request to fail.
    This usually means a network connection problem or that Jenkins is being restarted.
    Don't worry, reloading the page should help :-)

This then stays there forever.

Needless to say, it is somewhat hard to click a button on a wall display. And I wouldn't want to do this every couple of hours anyway.

So why can't it simply retry by itself, if there is a temporary connection problem? This somehow defeats the purpose of a wall display. I cannot go to all our offices and click that button, every time we restart our Jenkins master.

**Comment by jan-molak** [comment]
Hi @marc-guenther and thanks for your feedback. 

It might be interesting to find out *why* is your server is returning a `502 Bad Gateway` every couple of hours - perhaps there's a problem with a HTTP proxy you have in front of it? I'd imagine that the behaviour of a correct Jenkins installation should be that it doesn't do that :-)
Another thing is that when a Jenkins server is restarted it returns a `404` rather than a `502` and Build Monitor should already [respond to that correctly](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/cd3d6643235ecaaa98ddff79bbc55f06524f6541/src/main/webapp/scripts/controllers.js#L66).

To answer your question though - I agree, it might be a good idea for the Build Monitor to cater for those kinds of problems. I'll add your request to the backlog, but if you'd like to help out and submit a pull request that would be greatly appreciated. Here's where Build Monitor does Jenkins error handling: [controllers.js](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/cd3d6643235ecaaa98ddff79bbc55f06524f6541/src/main/webapp/scripts/controllers.js#L63) and [instructions](https://github.com/jan-molak/jenkins-build-monitor-plugin/wiki/Development-Guide) on setting up a dev environment.

Looking forward to hearing from you,
Jan

**Comment by marc-guenther** [comment]
Hi, thanks for your quick reply.

So, about the 502, I have no idea so far, it happens very sporadically. But I tried to simple shutdown Jenkins, and then when I access it, I get a 503 in the browser, not a 404. We are running a simple apache in front of Jenkins, which I think is a common setup.

So I think it might make sense to add the 503 (and possibly the 502?) to the switch case statement you mentioned up there.

BTW, your documentation is fantastic!

Another comment from looking at the source, I see the 'jenkins:restarted' simply does a $window.location.reload(). Now, Jenkins sometimes has quite a delay when it restarts, during which time the port isn't available at all, so doing a simple reload in these cases you end up with a blank screen, that will never refresh. (This is all guess work, I never tried this)

Marc

**Comment by jan-molak** [comment]
Hey Marc,

Glad you like the docs and thanks for your kind words :-)

---

Here's a bit of a background on why I'm reloading the page without a delay.

Jenkins uses [Stapler](http://stapler.kohsuke.org/), which is [Kohsuke](http://kohsuke.org/)'s "http request handling engine".
In order to get the AJAX communication between the UI and Jenkins/Stapler working, Build Monitor needs to acquire a "request token" - [here](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/155b73565973ac81fe9628bbb0ed6daf8a6786b3/src/main/resources/com/smartcodeltd/jenkinsci/plugins/buildmonitor/BuildMonitorView/index.jelly#L74).

This token is only valid for as long as Jenkins is up and running and can only be generated on the server-side. What this basically means is that whenever Jenkins restarts you *have to* reload the page in order to get a new token.

Another thing is that if you try to use an invalid Stapler token after a restart, instead of giving you a `400 Bad Request`, Jenkins returns a `404 Not Found`... 

The way I interpret a `404` in this context is *Jenkins got rebooted, but is now ready to serve further requests. Your token is not valid, go get a new one* - but because I know that Jenkins got restarted (the `404`) I can just reload the page.

---

Going back to your idea - I guess the things to consider when handling `502` and `503`s are: *does a connection error mean a restart, ie. do we need a new token and a website reload?*, or *the token is still valid, just wait a minute and try again*.

Best,
Jan

**Comment by marc-guenther** [comment]
Re: my reload comment

I was confused there. I meant, you should not reload the page, while Jenkins is down (connection refused, or 503). Of course, when you get an 404, then Jenkins is up, and your behaviour then is completely correct.
----
Regarding the 503, if you simply reload in that case, the browser will show the 503 error message forever, and never recover. So that should be handled through ajax entirely, and then rely on the 404 to acquire another token?

Sorry, I don't know too much about the internals of stapler, hope this makes sense.
Marc

**Comment by jan-molak** [comment]
Yes, it makes perfect sense :) And I agree, 503 should be handled by ajax as a connection failure. 
Would you like to submit this change if it works in your setup?

**Comment by jan-molak** [comment]
@marc-guenther - please have a look at [this comment](https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/52#issuecomment-41083921). 

About a year ago @awlunsfo ran into a similar trouble with the server periodically returning a `502`, which turned out to be a problem with the proxy configuration.

**Comment by marc-guenther** [comment]
@jan-molak - thanks a lot. That hint about the 502 solved that problem, and your commit above fixed the 503 problem on restart.

Marc :)

**Comment by jan-molak** [comment]
Awesome, thanks for letting me know! Glad it helped :smiley:
