### ISSUE TITLE
Build monitor needs 30+ seconds to refresh

### ISSUE THREAD

**Issue by patrickdepinguin** [jan-molak/jenkins-build-monitor-plugin#151]
I've been using the Build Monitor for a while now, but lately it has become very very slow. The initial page load, and every refresh cycle, takes more than 30 seconds. On this monitor, there are only 11 jobs visible. The slow loading even happens when no jobs are being built.

I tried restarting Jenkins, to no avail.
This is using Build Monitor 1.6+build.142 (latest as of this writing). 

The time for each cycle can easily be determined using Firefox/Chrome's Web Developer Tools, in the Network tab. 

Do you have any idea on what can cause this? Is there anything I can do to help you find the problem?

**Comment by jan-molak** [comment]
Hey @patrickdepinguin, it's good to hear from you again!

This sounds very strange as there haven't been any changes to the UI that could affect the performance in a negative way.

How's the performance of other Jenkins pages? List views for example? It's been reported (#74) that some security plugins can significantly affect the performance of Jenkins. Have you installed any of those by any chance?

**Comment by patrickdepinguin** [comment]
Hi @jan-molak, 
The performance of other pages in Jenkins is good, including for example the 'All' list view (say, 1 second load time). Just before filing this issue, I was on build132 and the behavior was already slow at that point.
Regarding plugins, we don't have the Role Strategy plugin mentioned in #74 installed.

However, I played a little more with a test Build Monitor view, and now concluded that the slow loading time is directly related to failing jobs being present in the view, more specifically: failing jobs with a culprit list.
A standard failing job without version control link and thus no list of possible culprits does not add to the loading time.
However, adding a failing job with culprits to the view, severely increases the load time, even if the 'show culprits' option is disabled.

Strangely enough, the list of commits associated with a job does not seem to be related, on the contrary: a job that currently has 21 commits adds about 30 seconds to the loading time, while another job that happens to have 446 commits adds only 10 seconds.

Given this new information: do you have an idea on how to optimize this?

**Comment by drekbour** [comment]
If it's repeatable (every load and not just the first when something has changed) then it's not SCM lookups as those are cached. Have you changed your authentication setup? Jenkins' getCulprits calls User.get(id) for each culprit each time. While I'd hope that's quick, I have no idea what it does under the covers.

**Comment by patrickdepinguin** [comment]
There are only a very limited (<10) number of real users on this instance. Triggered by your response, I checked the amount of users in 'People', which is about 550. These users are collected from SCM data.
I tried deleting them in batch to verify if that is related, but did not succeed. Do you know how to delete these automatically deleted users?
Could this be related?

**Comment by patrickdepinguin** [comment]
Looking at the code, I see that getCulprits() is called twice: once in shouldIndicateCulprits, and a second time to show the culprits from the Jelly code.
To solve my issue, I think it should never be called, for example by making sure that the 'Show culprits' is not simply switching a CSS .display setting.

public boolean shouldIndicateCulprits() {
    return ! isClaimed() && culprits().size() > 0;
}

**Comment by patrickdepinguin** [comment]
Hi @jan-molak, I thought "Let's fix this" but soon bumped into endless Java/Jenkins hell which I know almost nothing about. Finally I gave up and just deleted all culprit related code and tests. With this black build I get almost instant response when loading the monitor.

Obviously this is not upstreamable, but I hope that you can help in implementing the real solution. What I wanted to do was create a checkbox showCulprits on the settings page (BuildMonitorView/configure-entries.jelly). I struggled with how to make this persistent (and failed). 
If you could give me some code for that, I can probably progress a bit further with the actual changes.

Thanks in advance...

**Comment by jan-molak** [comment]
It should be easier to achieve with @drekbour's Config class introduced recently (#157). I'll try to give you some examples over the next couple of days (probably the weekend).

**Comment by patrickdepinguin** [comment]
I pulled today so already have these changes in my repository. I did indeed add some code in that Config class, but still failed.
I find many parts of Jenkins development to be ill-documented; for example how to add a checkbox in a Jelly file and which corresponding handling code is necessary. The 'documentation' that I can find is either too generic without giving the precise details, or too specific for one case. When looking at code from existing plugins, everyone seems to do it in their own way. I may be looking in the wrong places, of course, or just not in the right Java mindset ;-)

Anyway, I look forward to your examples, thanks!

**Comment by patrickdepinguin** [comment]
Kind reminder...

**Comment by jan-molak** [comment]
Apologies for not responding earlier, @patrickdepinguin. I was a bit busy with my other open source projects (such as the [release candidate](http://smartcodeltd.co.uk/release-candidate-maven-plugin/) plugin for maven, which Build Monitor will start using soon as well).

I agree with your point on Jenkins documentation - the approach I usually take in this case is to look under the hood of other Jenkins plugins as well as Jenkins itself and play a detective ... 

To answer your question about the examples though, I'm wondering if it's worth considering a config option where users would specify how many "top culprits" they want to display, rather than if they want to display them or not (this way a config option would be an input box rather than a checkbox).

If that's the approach we wanted to take, the following would need to be done:
* an input box would need to be added to [configure-entries.jelly](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/e3445a62f4e8bd16fce6ed96ea0d7fd4d4f1cb7d/src/main/resources/com/smartcodeltd/jenkinsci/plugins/buildmonitor/BuildMonitorView/configure-entries.jelly) - [basic guide to jelly usage in Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Basic+guide+to+Jelly+usage+in+Jenkins) might be useful here
* when the config form is submitted, the value from the input box (or a checkbox if that's your preference) would need to be validated in the [`:: submit(StaplerRequest req)`](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/e3445a62f4e8bd16fce6ed96ea0d7fd4d4f1cb7d/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/BuildMonitorView.java#L104) method and then assigned to the [Config](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/e3445a62f4e8bd16fce6ed96ea0d7fd4d4f1cb7d/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/Config.java) object
* with the above in place, the [`:: culprits()`](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/e3445a62f4e8bd16fce6ed96ea0d7fd4d4f1cb7d/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobView.java#L112) method of the [JobView](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/e3445a62f4e8bd16fce6ed96ea0d7fd4d4f1cb7d/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobView.java) class would need to be changed to incorporate the config option and stop processing the chain of builds once the limit is reached

Hope this helps!
