### ISSUE TITLE
Reporting: build-failure-analyzer-plugin, need to know unit test case broken with each commit

### ISSUE THREAD

**Issue by AmrutaM** [jan-molak/jenkins-build-monitor-plugin#170]
Hi,
I was checking CI tool which can be helpful to me to do automatic analysis from the build and can tell me test cases are broken due to which code commit.

I have tried to use build-failure-analyzer-plugin: added regex patterns but seems that is not sufficient as i need to filter with each new commit what are the new broken UTs.  As there is a possiblity where let's say with revision no: 1, two test cases are broken; after sometime there is another commit with which i can see there are 3 more test cases broke. In such cases how to differentiate which code has broken which test cases.

**Comment by diogoeag** [comment]
Anyone got a way to ake this working on multi-module projects? It would be interesting to get this info from Xunit plugin (https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin)

**Comment by jan-molak** [comment]
I'm trying to limit the amount of data displayed on the dashboard, but agree that showing some fancy charts and trends over time would be helpful. Maybe we should add a detailed view for each job where all this stuff could live?

**Comment by diogoeag** [comment]
Probably I didn't express myself correctly. The information that I would like to see is the same, but you can't get that on a multi-module project with a regex. Imagine a project like jetty (https://github.com/eclipse/jetty.project) if you build the project, it has at least 50 modules in root level. So you will find 50 matches to the string "Tests run: (\d+), Failures: (1d+), Errors: (\d+), Skipped: (\d+)". what would be interesting is to get the aggregated version of the results which is what jenkins does in the build page (like in the screenshot bellow):

![image](https://cloud.githubusercontent.com/assets/758998/16085759/0bd4da56-3315-11e6-8a4b-16bd61f1fc25.png)

**Comment by jan-molak** [comment]
Thanks @diogoeag, I see what you mean. I agree, the build description set using a regex is merely a stopgap on the way to something better :)
 
The challenge here is that there's a number of other statistics, similar to the number of tests, that people would be interested to see. Those could be: test coverage, checkstyle errors, PMD errors, FindBugs errors and many others.

Given all those, if we decided to show them all on the screen at the same time, we'd clutter the display.

So I guess we could either:
- display a textual representation of the current state of the stats on a single line and cycle through them somehow (maybe something like a stock-ticker could work?) This means that instead of the build description we'd see something along the lines of: `Test results: 120 passed, 7 failed, +5 failures since last run. Code coverage: 80%, +3% since last run, Checkstyle: ... etc.`)
- create an additional "detailed view" that you'd see when you click the project name. That view would tell you all about the build details and stats. That's however duplicating the functionality that Jenkins already provides..
- or do something else?

Thoughts?

**Comment by dmkamin** [comment]
Hi,

I'm trying to use the Build Failure Analyzer plugin to show the amount of failed test out of executed tests in the build monitor view.
Something like was mentioned above: Test results: 120 passed, 7 failed, +5 failures 
I had followed the plugin page and at the moment, I get the exception of failed tests inside the job box on the build monitor view. 
How can I parse the tests result and forward a specific value to the job box in the view.
I ad using testng (not junit) to execute the tests.
I have some post action in my tests job, that parse the result and create an html which includes the number of failed test. If possible, I can use that.

Thanks in advance, 
Michal

**Comment by jan-molak** [comment]
Hey Michal, did you have a chance to look at [the acceptance tests](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/Serenity/)? They explain the process of setting it up step by step (as per the [release notes](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases)). Hopefully the "Displaying The Number Of Failed Tests" should be of help. If it's not - please do let me know!

**Comment by dmkamin** [comment]
Hey Jan,
Thank you for the details.
I wasn't able to open the 'traditional user guide with acceptance tests' that you had mentioned in the release note, but managed to follow the release note and relevant links in it to get the test failures cause in the build monitor view :)
I still get the 'X builds have failed since ... committed their changes' statement.
DO you know how I can avoid having that in the Dashboard view?

Thanks in Advance, Michal

**Comment by jan-molak** [comment]
Cool, glad that it helped! This feature is not yet configurable, the easiest way to get rid of it is to have a successful build ;-)
