### ISSUE TITLE
Build Monitor View Continually Restarts and Throws Console Errors

### ISSUE THREAD

**Issue by jordan-parmer** [jan-molak/jenkins-build-monitor-plugin#182]
When creating a new 'Build Monitor View' (with or without jobs filtered), the page constantly refreshes. I've attached a screenshot of the two console errors I see. 

In hudson-bahavior.js on line 2063, the 'if' statement throws the error "isRunAsTest is not defined". Also seeing "YAHOO.widget.Tooltip is not a function". 

```
function ElementResizeTracker() {
    this.trackedElements = [];

    if(isRunAsTest) {
        return;
    }
```

This is on build 1.6+build.162.

<img width="1440" alt="screen shot 2015-11-06 at 1 27 10 pm" src="https://cloud.githubusercontent.com/assets/5378348/11006701/cdeb6266-848a-11e5-883d-c0347f272f57.png">

**Comment by jan-molak** [comment]
Hey @jordan-parmer and thanks for reporting this.

Those are probably two issues you're seeing, not necessarily related to each other:
* the first problem is the JS error - that was caused by one of the JavaScript dependencies (`hudson_behavior.js` script) looking for global variables and not being able to find them. This problem should be resolved in Build Monitor [1.6 build 163](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases/tag/v1.6%2Bbuild.163) where this dependency is gone.
* the second problem are the restarts, this could be caused by your Jenkins instance (or a HTTP proxy in front of it?) returning responses with the status code of `404`. As you can see in [this error handler](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/117ef2a3034101db825a42bcbc6717eeac27a436/src/main/webapp/scripts/controllers.js#L66), Build Monitor will only restart itself if Jenkins returns a `404`, and this should only happen when Jenkins is restarted.

Would you mind upgrading to [the latest version](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases/tag/v1.6%2Bbuild.163) of Build Monitor to see if the first problem is gone, and pasting http requests/responses that precede the restart so that I can help you investigate the second problem further?

Many thanks,
Jan

**Comment by jordan-parmer** [comment]
Thanks Jan for the quick turnaround! Yes, the new build fixed the first issue. 

Here is the request that is failing on the second issue: 

POST https://<hostname>/$stapler/bound/d4eb55d0-b945-44b0-8c52-3acc4aa845f3/fetchJobViews

I'll do some traffic analysis to see if I can capture more details. I'll post back later in the day with what I find.

**Comment by jordan-parmer** [comment]
What's interesting is that this works fine from a Windows machine and gets the 404 on a Mac machine.

**Comment by jordan-parmer** [comment]
Okay, looks like we've got a security issue on our end. I'm going to close this issue for now. Thanks for all your help!

**Comment by jan-molak** [comment]
No worries, happy to help!
