### ISSUE TITLE
Misconfigured corporate proxies: Regular "Sorry to bother you, but these is a slight issue..." error

### ISSUE THREAD

**Issue by nickcodefresh** [jan-molak/jenkins-build-monitor-plugin#197]
Hi,

At least a couple of times a day I'm getting the attached error, which i have to dismiss. As soon as I dismiss it, everything it working fine again.

![img_20160120_082426](https://cloud.githubusercontent.com/assets/5837418/12443659/4a1c1988-bf51-11e5-98df-d0cdd13cd9be.jpg)

I'm guessing that Jenkins is busy doing something (as the network isn't busy to the best of my knowledge, and Jenkins definitely isn't restarting), hence the 504. Would it be possible to add a certain number of automatic retries before displaying this error?

Thanks

Nick

**Comment by jan-molak** [comment]
Hey Nick,

I'm guessing that you have a proxy in front of Jenkins, is that correct? The `504` is quite possibly caused by the proxy being a bit too impatient with Jenkins, timing out and returning a `504` to your Build Monitor.

If you have a proxy in front of Jenkins, perhaps you'd like to consider increasing the timeout?

Looking forward to hearing from you!
Jan

**Comment by mbyrne00** [comment]
Hi Jan,

Many of us who experience this problem with proxy timeouts are behind a corporate proxy that we have no control over. Would it be possible to have an option to auto-refresh if we get 504 instead of requiring a button press? The problem is intermittent and reloading the page fixes it, so it would be nice if this happened automatically.

Cheers

**Comment by jan-molak** [comment]
Hey @mbyrne00, yeah, looks like misconfigured corporate proxies are a bit of a nightmare for many devs :-/

It would probably make sense to make a couple of (how many?) calls and should they all come back with `504` - display the error dialog. I'm not sure if refreshing automatically will solve the problem because you'd just end up on a `504` page for your corpo-proxy.

I'm thinking that to solve this we'd need a similar poller with a failure counter as we have for the [lost connections](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/14ad61aa52c78158861706f50d51fdc9bd9b7a9c/src/main/webapp/scripts/controllers.js#L59) case.

PRs welcome! :smiley:

**Comment by mbyrne00** [comment]
Thanks Jan, that all makes sense. I'll fork and take a look through the code on my train journeys.

**Comment by subos2008** [comment]
+1, this makes the plugin useless. I don't ever see 504s in any other context than this plugin reporting them.

**Comment by m1001** [comment]
+1
