### ISSUE TITLE
Aborted build are displayed as failed - red. should be gray.

### ISSUE THREAD

**Issue by avnerht** [jan-molak/jenkins-build-monitor-plugin#205]
The build status color should reflect the real status - green yellow red or gray.

**Comment by jan-molak** [comment]
Hi @avnerht and thanks for your feedback. This ticket duplicates #103, would you like to join the conversation there?

**Comment by avnerht** [comment]
Yes please

I must say it is really confusing
and i hope you will fix that
Thanks!

בתאריך יום ה׳, 18 בפבר׳ 2016, 17:07 מאת Jan Molak <notifications@github.com

**Comment by jan-molak** [comment]
Sorry you found it confusing :disappointed: The logic behind it was that if the build is aborted, it means there's a problem with it and that's why it's reported as "red". It seems like it might be useful to mark it as grey and mark the disabled builds with something, well, other than grey so that the mental mapping between Jenkins and Build Monitor colour schemes remains the same.

**Comment by avnerht** [comment]
Thanks for understanding our view ☺

Some of our builds aborted automatically in some cases other than failures
or timeout.

Maybe you can let the administrator decide the color-to-state mapping.

This is a good opportunity to say your plugin is very useful and we like it
very much!

Avner Hartuv.

בתאריך יום ו׳, 19 בפבר׳ 2016, 18:09 מאת Jan Molak <notifications@github.com
