### ISSUE TITLE
No valid crumb in Jenkins 2.0

### ISSUE THREAD

**Issue by Roystoned** [jan-molak/jenkins-build-monitor-plugin#215]
Getting this error since Jenkins 2.0
Apr 22, 2016 5:11:53 PM hudson.security.csrf.CrumbFilter doFilter
WARNING: No valid crumb was included in request for /$stapler/bound/***/fetchJobViews. Returning 403.

**Comment by appienvanveen** [comment]
Got this issue too!

**Comment by eduardtomasek** [comment]
Same issue :)

**Comment by jan-molak** [comment]
Hey guys and thanks for highlighting this issue, I'll have a look and see what can be done.

From what I can tell by looking at the Jenkins Jira, there's been some problems reported around those crumb headers causing trouble in different parts of Jenkins, so maybe something significant has changed that broke backwards compatibility? I'll need to investigate that.

A workaround that's recommended in Jenkins forums is to disable the CSRF protection (Jenkins / Manage Jenkins / Configure Global Security -> disable 'Prevent Cross Site Request Forgery exploits'), so you might want to consider that for the time being.

**Comment by jan-molak** [comment]
@Roystoned, @appienvanveen, @eduardtomasek, the [latest build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/37/artifact/build-monitor-plugin/target/build-monitor-plugin.hpi) should resolve this problem.
Please feel free to experiment with it and let me know if it fixes the issue for you.

**Comment by appienvanveen** [comment]
Fixes it for me! Thanks!

**Comment by peschmae0** [comment]
Works perfectly now, thanks for the build

**Comment by jan-molak** [comment]
Excellent, thanks for confirming!

**Comment by pgrm** [comment]
Hey, I've just set up jenkins 2.5 on windows and am experiencing the same (or a very similar) issue as described in https://issues.jenkins-ci.org/browse/JENKINS-12875 This is what I see on *Console Output* of a running job:

    HTTP ERROR 403
    
    
    Problem accessing /"SOME PATH"/logText/progressiveHtml. Reason:
    
        No valid crumb was included in the request
    Powered by Jetty://

When I click to **View as plain text** and the browser goes to *http://...../consoleText* than I can see the output. And when I press the back button of the browser, I can see it also in the *Console Output* - until I reload the page again.

**Comment by jan-molak** [comment]
Hey @pgrm, 

The reason why Build Monitor is mentioned in [JENKINS-12875](https://issues.jenkins-ci.org/browse/JENKINS-12875) is because it was affected by a change introduced in Jenkins 2.0.
The change in question (described on that ticket) improves Jenkins' cooperation with Nginx, but has a side effect on some plugins including the Build Monitor (those plugins have made an incorrect assumption that if the crumb header hasn't changed since 2008 then it never would... well, it just has and that's why we get the "no valid crumb error" ;-) ).

Build Monitor has been fixed since then, but as the Console Output view is rendered by Jenkins itself rather than the Build Monitor plugin, it could be that one of other plugins you're using is still suffering from the same problem?

I'm guessing that the best thing for you to try is to describe the problem on [JENKINS-12875](https://issues.jenkins-ci.org/browse/JENKINS-12875).

Hope this helps,
Jan

**Comment by jalessio** [comment]
For anyone getting a 404 on the link to "the latest build" linked above by @jan-molak it appears that you just need to link to an even newer build...

Follow this link, then click on the builds on the left and find the latest "artifacts":
https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/

For example, as of now, the latest build artifact resides here:
https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/43/artifact/build-monitor-plugin/target/build-monitor-plugin.hpi

**Comment by jan-molak** [comment]
Thanks for pointing this out, @jalessio! I've updated the link 👍 
The latest build is now also available on Jenkins Update Center and [here you can find the changelog](https://bit.ly/JBMReleases)
