### ISSUE TITLE
Ability to remove text from names of jobs

### ISSUE THREAD

**Issue by stephaneerard** [jan-molak/jenkins-build-monitor-plugin#219]
Hello,

I use pattern matching, thus I get repeated texts like

MY-PROJECT-FEATURE-x
MY-PROJECT-FEATURE-y

It takes all the space of the screen.
Having possibility to remove some text would be a great win at little cost.

Here, I'd like to be able to configure the plugin to output :
x
y

Thus configuring it to remove the text "MY-PROJECT-FEATURE-"

Thank you very much !

**Comment by jan-molak** [comment]
Hey @stephaneerard and thanks for the suggestion! 

Build Monitor uses the "Display name" rather than the "Name" attribute of a job if one is set. 
Would that work in your case?

<img width="601" alt="screen shot 2016-05-10 at 19 23 38" src="https://cloud.githubusercontent.com/assets/1089173/15157730/c4aa07ce-16e4-11e6-98c4-fca9dd19af25.png">
