### ISSUE TITLE
Image that is defined by build description in test results shows fullsize image in build monitor view

### ISSUE THREAD

**Issue by pZq** [jan-molak/jenkins-build-monitor-plugin#261]
Image in test result show fullsize image in build monitor view while in the hudson view shows as defined.

The definition is like below:
![image](https://cloud.githubusercontent.com/assets/6633097/19114688/b00173e6-8b17-11e6-9bbe-7e576502d7e3.png)

In hudson view it shows like this:
![image](https://cloud.githubusercontent.com/assets/6633097/19114713/d8631952-8b17-11e6-95e1-738704c47d6e.png)

In build monitor view it shows:
![image](https://cloud.githubusercontent.com/assets/6633097/19114983/f1724444-8b18-11e6-91ac-8a697b532e8f.png)

Could this be fixed so that the img would be as defined in the build description function ?
##

**Comment by pZq** [comment]
Hi, thank you for replying.

My build results are showing my testruns for GUI Tests only and at failure,
a screenshot is taken. This screenshot generates a path link where i can
find the image within the console output. Injenkins im parsing the result
output with regexp to replace "screenshot here" with an  <img> tag and
giving the img tag style="height: 100px;" making it show nicely small in
jenkins hudson layout but in buil monitor view the image content is full
size, thus blocking many test results from the shown area of results on
monitor. I.e.This feature would show more results on the monitor. Now it
basically shows 1 test if a fail is found.

Br.
-pZq


On Jan 16, 2017 03:25, "Jan Molak" <notifications@github.com> wrote:

Hey @pZq <https://github.com/pZq> and thanks for reporting this. That's a
tricky one because the build description can contain valid HTML (a link to
a build artifact, for example).

Could you please elaborate a bit more on why you'd like to set the build
description to an image and what's the behaviour you'd expect from Build
Monitor?

Thanks,
Jan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/261#issuecomment-272754262>,
or mute the thread

**Comment by jan-molak** [comment]
Cool, thanks for the explanation.

You can solve this problem in at least two ways:

### Option 1:

Instead of setting the description to `<img src="..." style="height: 100px" />` use the old-school `height` attribute of the `<img />` tag so that you have: `<img src="..." height="100">`, which will result in something like this:

<img width="469" alt="screen shot 2017-01-16 at 02 33 35" src="https://cloud.githubusercontent.com/assets/1089173/21969203/383e40be-db94-11e6-87f8-ac0a7396e09a.png">

The disadvantage of this approach is that your build history on Jenkins will become messy:
<img width="337" alt="screen shot 2017-01-16 at 02 35 11" src="https://cloud.githubusercontent.com/assets/1089173/21969231/82043d02-db94-11e6-9d31-8e99f4a4b10b.png">

### Option 2

Think of the screenshot as yet another artifact of your build that you want to track.

Configure a post-build action to archive the screenshot so that it's stored together with the build metadata and other artifacts, if any (remember that you can configure Jenkins to discard old build if you're worried about the disk space usage):
<img width="278" alt="screen shot 2017-01-16 at 02 31 30" src="https://cloud.githubusercontent.com/assets/1089173/21969300/20ff0324-db95-11e6-9ffd-edb26c010717.png">

Once you have the screenshot archived you can set the build description to a text link, which points to that archived screenshot if you want to, but you'll also have the screenshot listed together with other artifacts on the build details page.

Hope this helps!
Jan

**Comment by pZq** [comment]
Thanks for the tips!

I will try if im satisfied with the outcome of your suggestion :)

I havent looked into artifacts at or what the definition of artifacts is...
But dont explain. I will do the learning by my self :)

Thank you for the tips again!

-pZq
