### ISSUE TITLE
Consistency with last build's description and badge

### ISSUE THREAD

**Issue by johnbieren** [jan-molak/jenkins-build-monitor-plugin#287]
Hello,
With the latest released version of the build monitor plugin, when a new build starts, the bottom left of the job's visual updates to the latest build name and the previous build's description is also cleared as the new build starts.  However, the previous build's groovy badge will still remain, which seems a little misleading to me, as everything else on the visual is changed with the new build in progress, except the badge.  Can the badge also be removed when a new build starts?
Thanks!

**Comment by jan-molak** [comment]
Hey @johnbieren and thanks for reporting this. That's a good point; I'll look into this when I have a moment and am also happy to accept pull requests solving this problem.

**Comment by vit0rg** [comment]
As long as we have color of previous build still showing on progress (red if previous build has failed), we need to see badges from previous build because usually badges show us reason of previous build failure.
Also cleaning of badges can be done as first step of build which is mush easier than copying all of badges from previous build now.
