### ISSUE TITLE
Badges of previous build not displayed during job execution.

### ISSUE THREAD

**Issue by Xyaren** [jan-molak/jenkins-build-monitor-plugin#316]
With the new version (1.12+build.201704111018) the badges of the previous build are not displayed on the current running tile.

This is a very unfortunate behaviour for long & frequent running jobs, because there is only a very very short timespan for batches to be shown.

**Comment by dcendents** [comment]
Hi @Xyaren, yeah my PR #301 "fixed" that (see issue #287). I suppose different people expect different things, it will be hard to get a single behavior which pleases everybody.

If you are using pipelines, try to add the badges as soon as you have the information available. Another option could be to copy the badges from the previous build at the beginning of the job and delete/re-create them with the new values at the end of the build.

**Comment by Xyaren** [comment]
Maybe add an option to the View settings where you can enable/disable the "clearing" of the badges on  job start ?

**Comment by vit0rg** [comment]
Agree with @Xyaren, new behaviour is pretty useless, as long as we have color of previous build still showing on progress (red if previous build has failed), we need to see badges from previous build because usually badges show us reason of previous build failure. I guess #287 isn't an issue and #301 should be rolled back or be an option in settings.

**Comment by vit0rg** [comment]
Also cleaning of badges can be done as first step of build which is mush easier than copying all of badges from previous build now.
