### ISSUE TITLE
Feature request: ability to hide culprits

### ISSUE THREAD

**Issue by patrickdepinguin** [jan-molak/jenkins-build-monitor-plugin#70]
The plugin by default shows culprits for failed builds, but this is not always desired.
I could work around this by editing the css manually (display:none) but a configuration option would be nice.

**Comment by cialx** [comment]
Hi Jan,
why was this feature removed? We still want to hide culprits, because the workers' council told us we are not allowed to show them on a wall board for everybody to see.
Greetings and thank you for your help, cialx

**Comment by jan-molak** [comment]
Hey @cialx it was removed because it seemed redundant - when a broken build gets claimed the culprit names are no longer displayed.

Claiming broken builds promotes transparency and encourages taking ownership of the problem. Have you tried using [the Claim plugin](https://wiki.jenkins-ci.org/display/JENKINS/Claim+plugin) perhaps?

Having said that - can you tell me more about the workers' council and their rationale? I'm curious, is there any specific legal or personal data protection issue that they're concerned about that we should be taking into consideration?

Thanks!
Jan

**Comment by cialx** [comment]
Tyvm for replying so soon!
We want to use as little plugins as possible, but if this is the only way to solve our problem, we will do that. Can broken builds be claimed automatically somehow?
The workers' council criticised that people are blamed publically, especially since our CI wall display is in the hallway for other departments to see. It's not related to data protection (the names of all deparment members are shown on the display as well).
